{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ template "eks-ng-ami-updater.name" . }}
  name: {{ template "eks-ng-ami-updater.serviceAccountName" . }}
  labels:
    app: {{ template "eks-ng-ami-updater.name" . }}
    chart: {{ template "eks-ng-ami-updater.chart" . }}
    release: {{ .Release.Name }}
{{- end }}